package gmqb

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExpr_Coverage(t *testing.T) {
	assert.NotNil(t, ExprConcat("a", "b"))
	assert.NotNil(t, ExprSubstr(0, 0, 0))
	assert.NotNil(t, ExprToLower(0))
	assert.NotNil(t, ExprToUpper(0))
	assert.NotNil(t, ExprTrim(0, 0))
	assert.NotNil(t, ExprLTrim(0, 0))
	assert.NotNil(t, ExprRTrim(0, 0))
	assert.NotNil(t, ExprStrLenCP(0))
	assert.NotNil(t, ExprRegexMatch(0, "", ""))
	assert.NotNil(t, ExprRegexFind(0, "", ""))
	assert.NotNil(t, ExprRegexFindAll(0, "", ""))
	assert.NotNil(t, ExprSplit(nil, 0))
	assert.NotNil(t, ExprReplaceOne(nil, nil, 0))
	assert.NotNil(t, ExprReplaceAll(nil, nil, 0))
	assert.NotNil(t, ExprArrayElemAt(0, 0))
	assert.NotNil(t, ExprConcatArrays("a", "b"))
	assert.NotNil(t, ExprFilter(0, "", 0))
	assert.NotNil(t, ExprIsArray(0))
	assert.NotNil(t, ExprMap(0, "", 0))
	assert.NotNil(t, ExprReduce(nil, nil, 0))
	assert.NotNil(t, ExprSlice(0, 1, 2))
	assert.NotNil(t, ExprIn(nil, 0))
	assert.NotNil(t, ExprIndexOfArray(nil, 0))
	assert.NotNil(t, ExprReverseArray(0))
	assert.NotNil(t, ExprSortArray(0, 0))
	assert.NotNil(t, ExprZip(nil, false, nil))
	assert.NotNil(t, ExprObjectToArray(0))
	assert.NotNil(t, ExprArrayToObject(0))
	assert.NotNil(t, ExprDateFromString(0, nil, 0))
	assert.NotNil(t, ExprDateToString(0, nil, 0))
	assert.NotNil(t, ExprDateAdd(0, "", 0))
	assert.NotNil(t, ExprDateSubtract(0, "", 0))
	assert.NotNil(t, ExprDateDiff(nil, 0, ""))
	assert.NotNil(t, ExprDateTrunc(0, ""))
	assert.NotNil(t, ExprYear(0))
	assert.NotNil(t, ExprMonth(0))
	assert.NotNil(t, ExprDayOfMonth(0))
	assert.NotNil(t, ExprHour(0))
	assert.NotNil(t, ExprMinute(0))
	assert.NotNil(t, ExprSecond(0))
	assert.NotNil(t, ExprMillisecond(0))
	assert.NotNil(t, ExprDayOfWeek(0))
	assert.NotNil(t, ExprDayOfYear(0))
	assert.NotNil(t, ExprISOWeek(0))
	assert.NotNil(t, ExprISOWeekYear(0))
	assert.NotNil(t, ExprConvert(0, 0, nil, 0))
	assert.NotNil(t, ExprToBool(0))
	assert.NotNil(t, ExprToInt(0))
	assert.NotNil(t, ExprToLong(0))
	assert.NotNil(t, ExprToDouble(0))
	assert.NotNil(t, ExprToDecimal(0))
	assert.NotNil(t, ExprToString(0))
	assert.NotNil(t, ExprToObjectId(0))
	assert.NotNil(t, ExprToDate(0))
	assert.NotNil(t, ExprType(0))
	assert.NotNil(t, ExprIsNumber(0))
	assert.NotNil(t, ExprAdd("a", "b"))
	assert.NotNil(t, ExprSubtract(nil, 0))
	assert.NotNil(t, ExprMultiply("a", "b"))
	assert.NotNil(t, ExprDivide(nil, 0))
	assert.NotNil(t, ExprMod(nil, 0))
	assert.NotNil(t, ExprAbs(0))
	assert.NotNil(t, ExprCeil(0))
	assert.NotNil(t, ExprFloor(0))
	assert.NotNil(t, ExprRound(0, 0))
	assert.NotNil(t, ExprPow(nil, 0))
	assert.NotNil(t, ExprSqrt(0))
	assert.NotNil(t, ExprLog(nil, 0))
	assert.NotNil(t, ExprLn(0))
	assert.NotNil(t, ExprCmp(nil, 0))
	assert.NotNil(t, ExprEq(nil, 0))
	assert.NotNil(t, ExprNe(nil, 0))
	assert.NotNil(t, ExprGt(nil, 0))
	assert.NotNil(t, ExprGte(nil, 0))
	assert.NotNil(t, ExprLt(nil, 0))
	assert.NotNil(t, ExprLte(nil, 0))
	assert.NotNil(t, ExprBoolAnd("a", "b"))
	assert.NotNil(t, ExprBoolOr("a", "b"))
	assert.NotNil(t, ExprBoolNot(0))
	assert.NotNil(t, ExprCond(false, nil, 0))
	assert.NotNil(t, ExprIfNull(nil, 0))
	assert.NotNil(t, ExprSwitch(nil, 0))
	assert.NotNil(t, AccSum(0))
	assert.NotNil(t, AccAvg(0))
	assert.NotNil(t, AccMin(0))
	assert.NotNil(t, AccMax(0))
	assert.NotNil(t, AccFirst(0))
	assert.NotNil(t, AccLast(0))
	assert.NotNil(t, AccPush(0))
	assert.NotNil(t, AccAddToSet(0))
	assert.NotNil(t, AccStdDevPop(0))
	assert.NotNil(t, AccStdDevSamp(0))
	assert.NotNil(t, AccCount())
	assert.NotNil(t, AccFirstN(0, 0))
	assert.NotNil(t, AccLastN(0, 0))
	assert.NotNil(t, AccMaxN(0, 0))
	assert.NotNil(t, AccMinN(0, 0))
	assert.NotNil(t, AccTop(nil, 0))
	assert.NotNil(t, AccBottom(nil, 0))
	assert.NotNil(t, AccTopN(nil, 0, 0))
	assert.NotNil(t, AccBottomN(nil, 0, 0))
	assert.NotNil(t, AccMedian(0, ""))
	assert.NotNil(t, AccPercentile(0, nil, ""))
	assert.NotNil(t, ExprSetEquals("a", "b"))
	assert.NotNil(t, ExprSetIntersection("a", "b"))
	assert.NotNil(t, ExprSetUnion("a", "b"))
	assert.NotNil(t, ExprSetDifference(nil, 0))
	assert.NotNil(t, ExprSetIsSubset(nil, 0))
	assert.NotNil(t, ExprAnyElementTrue(0))
	assert.NotNil(t, ExprAllElementsTrue(0))
	assert.NotNil(t, ExprMergeObjects("a", "b"))
	assert.NotNil(t, ExprGetField(0, 0))
	assert.NotNil(t, ExprSetField(0, nil, 0))
	assert.NotNil(t, ExprUnsetField(0, 0))
	assert.NotNil(t, ExprLiteral(0))
	assert.NotNil(t, ExprRand())
	assert.NotNil(t, ExprSampleRate(0.5))
	assert.NotNil(t, ExprLet(nil, 0))
}
